$(document).ready(function () {
    // Smooth scrolling for navigation links
    $('a[href^="#"]').on('click', function(event) {
        const target = $(this.getAttribute('href'));
        if( target.length ) {
            event.preventDefault();
            $('html, body').stop().animate({
                scrollTop: target.offset().top
            }, 1000);
        }
    });

    // Define quiz questions // Added More Questions
    const questions = [
        { question: "Quelle est la définition de la grandeur physique ?", options: ["Caractéristique définie par une norme et une unité.", "Caractéristique d'un objet ou phénomène pouvant être mesuré.", "Caractéristique définie par une norme et une direction (vecteur)."], answer: "Caractéristique d'un objet ou phénomène pouvant être mesuré." },
        { question: "Qu'est-ce qu'une force pressante ?", options: ["Une force qui modélise une action mécanique de contact exercée par un solide.", "Il s’agit d’une force de poussée exercée lors du contact entre un fluide (un gaz ou un liquide) et un autre corps.", "Le dosage en volume des solutions."], answer: "Il s’agit d’une force de poussée exercée lors du contact entre un fluide (un gaz ou un liquide) et un autre corps." },
        { question: "Les lignes vectorielles sont :", options: ["Les courbes obtenues en reliant les points où la grandeur physique étudiée a la même valeur.", "Le vecteur qui le caractérise est le même en tout point de la région de l’espace étudiée : même direction, même sens et même valeur.", "Les courbes tangentes au vecteur champ en chacun de leurs points."], answer: "Les courbes tangentes au vecteur champ en chacun de leurs points." },
        { question: "Qu'est-ce que la pression atmosphérique ?", options: ["La force exercée par l'atmosphère sur une surface.", "La pression à laquelle une substance change d'état de liquide à gaz.", "La quantité d'oxygène présente dans l'air."], answer: "La force exercée par l'atmosphère sur une surface." },
        { question: "Quelle est la formule de la pression ?", options: ["P = m*g", "P = F/A", "P = V/T"], answer: "P = F/A" },
        { question: "Qu'est-ce que la densité d'un matériau ?", options: ["La masse par unité de surface.", "La masse par unité de longueur.", "La masse par unité de volume."], answer: "La masse par unité de volume." },
        { question: "Comment peut-on déterminer la densité d'un objet ?", options: ["En divisant sa masse par son volume.", "En multipliant sa masse par son volume.", "En additionnant sa masse et son volume."], answer: "En divisant sa masse par son volume." },
        { question: "Qu'est-ce que la force gravitationnelle ?", options: ["Une force qui pousse tous les objets dotés de masse.", "Une force qui attire tous les objets dotés de masse.", "Une force qui repousse tous les objets dotés de masse."], answer: "Une force qui attire tous les objets dotés de masse." },
        { question: "Qui a formulé les lois du mouvement ?", options: ["Albert Einstein", "Galilée", "Isaac Newton"], answer: "Isaac Newton" },
        { question: "Quelle est la première loi de Newton ?", options: ["Loi de l'inertie", "Loi de l'action et de la réaction", "Loi des moments"], answer: "Loi de l'inertie" },
        { question: "Quelle est la formule de la force ?", options: ["F = m/g", "F = m*a", "F = P/A"], answer: "F = m*a" },
        { question: "Quelle est l'unité de la force dans le Système International ?", options: ["Kilogramme (kg)", "Mètre par seconde carrée (m/s²)", "Newton (N)"], answer: "Newton (N)" },
        { question: "Qu'est-ce que la première loi de Kepler ?", options: ["Les planètes décrivent des orbites elliptiques autour du Soleil.", "Les aires balayées par le rayon vecteur sont proportionnelles au temps.", "Le carré de la période de révolution est proportionnel au cube de la distance moyenne au Soleil."], answer: "Les planètes décrivent des orbites elliptiques autour du Soleil." },
        { question: "Qu'est-ce que la seconde loi de Kepler ?", options: ["Les planètes décrivent des orbites elliptiques autour du Soleil.", "Les aires balayées par le rayon vecteur sont proportionnelles au temps.", "Le carré de la période de révolution est proportionnel au cube de la distance moyenne au Soleil."], answer: "Les aires balayées par le rayon vecteur sont proportionnelles au temps." },
        { question: "Qu'est-ce que la troisième loi de Kepler ?", options: ["Les aires balayées par le rayon vecteur sont proportionnelles au temps.", "Les planètes décrivent des orbites elliptiques autour du Soleil.", "Le carré de la période de révolution est proportionnel au cube de la distance moyenne au Soleil."], answer: "Le carré de la période de révolution est proportionnel au cube de la distance moyenne au Soleil." },
        { question: "Qu'est-ce que la réfraction de la lumière ?", options: ["Le changement de direction de la lumière lorsqu'elle passe d'un milieu à un autre.", "L'absorption de la lumière par un objet.", "La production de lumière par un matériau."], answer: "Le changement de direction de la lumière lorsqu'elle passe d'un milieu à un autre." },
        { question: "Quelle est la loi de la réfraction ?", options: ["La loi de Gauss", "La loi de Snell-Descartes", "La loi de Coulomb"], answer: "La loi de Snell-Descartes" },
        { question: "Qu'est-ce que l'indice de réfraction ?", options: ["Une mesure de la densité d'un matériau.", "Une mesure de la température d'un milieu.", "Une mesure de la vitesse de la lumière dans un milieu par rapport à sa vitesse dans le vide."], answer: "Une mesure de la vitesse de la lumière dans un milieu par rapport à sa vitesse dans le vide." },
        { question: "Qu'est-ce que la diffraction de la lumière ?", options: ["La propagation de la lumière dans toutes les directions après avoir rencontré un obstacle.", "Le changement de direction de la lumière lorsqu'elle passe d'un milieu à un autre.", "L'absorption de la lumière par un objet."], answer: "La propagation de la lumière dans toutes les directions après avoir rencontré un obstacle." },
        { question: "Qu'est-ce que la polarisation de la lumière ?", options: ["Le changement de couleur de la lumière.", "L'orientation des oscillations de la lumière dans un plan spécifique.", "La réfraction de la lumière à travers un prisme."], answer: "L'orientation des oscillations de la lumière dans un plan spécifique." },
        { question: "Quelle est la couleur complémentaire du rouge ?", options: ["Magenta", "Vert", "Cyan"], answer: "Cyan" },
        { question: "Quelle est la couleur complémentaire du vert ?", options: ["Magenta", "Cyan", "Jaune"], answer: "Magenta" },
        { question: "Quelle est la couleur complémentaire du bleu ?", options: ["Rouge", "Jaune", "Orange"], answer: "Jaune" },
        { question: "Qu'est-ce qu'un circuit électrique en série ?", options: ["Un circuit où les composants sont connectés parallèlement.", "Un circuit où il y a un seul composant.", "Un circuit où les composants sont connectés les uns après les autres."], answer: "Un circuit où les composants sont connectés les uns après les autres." },
        { question: "Qu'est-ce qu'un circuit électrique en parallèle ?", options: ["Un circuit où les composants sont connectés parallèlement.", "Un circuit où les composants sont connectés les uns après les autres.", "Un circuit où il y a un seul composant."], answer: "Un circuit où les composants sont connectés parallèlement." },
        { question: "Quelle est la différence entre un conducteur et un isolant ?", options: ["Un conducteur bloque le courant électrique, tandis qu'un isolant le permet.", "Un conducteur permet le passage du courant électrique, tandis qu'un isolant l'empêche.", "Il n'y a pas de différence."], answer: "Un conducteur permet le passage du courant électrique, tandis qu'un isolant l'empêche." },
        { question: "Qu'est-ce que la résistance électrique ?", options: ["La facilité avec laquelle un matériau laisse passer le courant électrique.", "La quantité de courant électrique dans un circuit.", "La propriété d'un matériau à s'opposer au passage du courant électrique."], answer: "La propriété d'un matériau à s'opposer au passage du courant électrique." },
        { question: "Quelle est la formule de la résistance électrique ?", options: ["R = V/I", "R = I/V", "R = P/I"], answer: "R = V/I" },
        { question: "Quelle est l'unité de la résistance électrique ?", options: ["Volt (V)", "Ohm (Ω)", "Ampère (A)"], answer: "Ohm (Ω)" },
        { question: "Qu'est-ce que la loi d'Ohm ?", options: ["La résistance dans un circuit est égale au produit de la tension par l'intensité du courant.", "La tension dans un circuit est égale au produit de la résistance par l'intensité du courant.", "L'intensité du courant dans un circuit est égale à la tension divisée par la résistance."], answer: "La tension dans un circuit est égale au produit de la résistance par l'intensité du courant." },
        { question: "Qu'est-ce que la capacité d'un condensateur ?", options: ["Sa capacité à conduire le courant électrique.", "Sa capacité à résister au passage du courant électrique.", "Sa capacité à stocker de la charge électrique."], answer: "Sa capacité à stocker de la charge électrique." },
        { question: "Quelle est l'unité de la capacité électrique ?", options: ["Farad (F)", "Ampère (A)", "Ohm (Ω)"], answer: "Farad (F)" },
        { question: "Qu'est-ce que la loi de Coulomb ?", options: ["Elle décrit la relation entre la tension, l'intensité et la résistance dans un circuit.", "Elle décrit l'interaction électrostatique entre des charges électriques.", "Elle décrit la relation entre la vitesse, la masse et le rayon de courbure d'un objet en mouvement circulaire."], answer: "Elle décrit l'interaction électrostatique entre des charges électriques." },
        { question: "Quelle est la formule de la loi de Coulomb ?", options: ["F = m * a", "F = P/A", "F = k * (|q1 * q2|) / r^2"], answer: "F = k * (|q1 * q2|) / r^2" },
        { question: "Qu'est-ce qu'un circuit en courant alternatif (AC) ?", options: ["Un circuit où le courant change périodiquement de direction.", "Un circuit où le courant circule dans une seule direction.", "Un circuit où le courant varie aléatoirement."], answer: "Un circuit où le courant change périodiquement de direction." },
        { question: "Qu'est-ce qu'un circuit en courant continu (DC) ?", options: ["Un circuit où le courant change périodiquement de direction.", "Un circuit où le courant circule dans une seule direction.", "Un circuit où le courant varie aléatoirement."], answer: "Un circuit où le courant circule dans une seule direction." },
        { question: "Quelle est la différence entre un aimant permanent et un électroaimant ?", options: ["Un aimant permanent est toujours magnétique, tandis qu'un électroaimant peut être activé ou désactivé en fonction du courant électrique qui le traverse.", "Il n'y a pas de différence.", "Un aimant permanent a un champ magnétique constant, tandis qu'un électroaimant a un champ magnétique variable."], answer: "Un aimant permanent est toujours magnétique, tandis qu'un électroaimant peut être activé ou désactivé en fonction du courant électrique qui le traverse." },
        { question: "Qu'est-ce que la loi de Lenz ?", options: ["Elle décrit le sens du courant induit dans un circuit par un champ magnétique variable.", "Elle décrit la relation entre la tension, l'intensité et la résistance dans un circuit.", "Elle décrit la relation entre la vitesse, la masse et le rayon de courbure d'un objet en mouvement circulaire."], answer: "Elle décrit le sens du courant induit dans un circuit par un champ magnétique variable." },
        { question: "Qu'est-ce que la loi de Faraday ?", options: ["Elle décrit la relation entre la tension, l'intensité et la résistance dans un circuit.", "Elle décrit l'induction électromagnétique, c'est-à-dire la création d'une force électromotrice dans un circuit par un champ magnétique variable.", "Elle décrit la relation entre la vitesse, la masse et le rayon de courbure d'un objet en mouvement circulaire."], answer: "Elle décrit l'induction électromagnétique, c'est-à-dire la création d'une force électromotrice dans un circuit par un champ magnétique variable." },
        { question: "Quelle est la formule de la loi de Faraday ?", options: ["ε = P/I", "ε = F/A", "ε = -dΦ/dt"], answer: "ε = -dΦ/dt" },
        { question: "Qu'est-ce qu'une onde électromagnétique ?", options: ["Une onde qui se propage à travers l'espace et le vide, composée de champs électriques et magnétiques oscillants perpendiculaires entre eux.", "Une onde qui se propage à travers un milieu matériel, composée de particules chargées électriquement.", "Une onde qui se propage à travers un milieu matériel, composée de photons."], answer: "Une onde qui se propage à travers l'espace et le vide, composée de champs électriques et magnétiques oscillants perpendiculaires entre eux." },
        { question: "Quelle est la vitesse de la lumière dans le vide ?", options: ["3 000 000 m/s", "299 792 458 m/s", "30 000 m/s"], answer: "299 792 458 m/s" },
        { question: "Quelle est la relation entre la fréquence (f) et la période (T) d'une onde ?", options: ["f = T", "f = T^2", "f = 1/T"], answer: "f = 1/T" },
        { question: "Quelle est la relation entre la longueur d'onde (λ) et la fréquence (f) d'une onde ?", options: ["v = λ*f", "v = λ/T", "v = f/T"], answer: "v = λ*f" },
        { question: "Quelle est la formule de l'énergie d'un photon ?", options: ["E = m*c^2", "E = h*f", "E = P*t"], answer: "E = h*f" },
        { question: "Qu'est-ce que l'énergie cinétique ?", options: ["L'énergie stockée dans un objet en raison de sa position.", "L'énergie associée aux vibrations d'un objet.", "L'énergie associée au mouvement d'un objet."], answer: "L'énergie associée au mouvement d'un objet." },
        { question: "Quelle est la formule de l'énergie cinétique ?", options: ["E = (1/2)*m*v^2", "E = m*g*h", "E = P*t"], answer: "E = (1/2)*m*v^2" },
        { question: "Qu'est-ce que l'énergie potentielle gravitationnelle ?", options: ["L'énergie associée au mouvement d'un objet.", "L'énergie stockée dans un objet en raison de sa position par rapport à la surface de la Terre.", "L'énergie associée aux vibrations d'un objet."], answer: "L'énergie stockée dans un objet en raison de sa position par rapport à la surface de la Terre." },
        { question: "Quelle est la formule de l'énergie potentielle gravitationnelle ?", options: ["E = (1/2)*m*v^2", "E = P*t", "E = m*g*h"], answer: "E = m*g*h" },
        { question: "Qu'est-ce que l'énergie potentielle élastique ?", options: ["L'énergie stockée dans un objet en raison de sa déformation.", "L'énergie associée au mouvement d'un objet.", "L'énergie associée aux vibrations d'un objet."], answer: "L'énergie stockée dans un objet en raison de sa déformation." },
        { question: "Quelle est la formule de l'énergie potentielle élastique ?", options: ["E = m*g*h", "E = (1/2)*k*x^2", "E = P*t"], answer: "E = (1/2)*k*x^2" },
        { question: "Qu'est-ce que la chaleur ?", options: ["L'énergie stockée dans un objet en raison de sa position par rapport à la surface de la Terre.", "L'énergie associée aux vibrations d'un objet.", "L'énergie transférée entre deux systèmes ou entre un système et son environnement du fait d'une différence de température."], answer: "L'énergie transférée entre deux systèmes ou entre un système et son environnement du fait d'une différence de température." },
        { question: "Quelle est l'unité de la chaleur dans le Système International ?", options: ["Joule (J)", "Watt (W)", "Calorie (cal)"], answer: "Joule (J)" },
        { question: "Quelle est la différence entre la chaleur spécifique et la capacité thermique ?", options: ["La chaleur spécifique est la quantité de chaleur nécessaire pour élever la température d'un objet entier d'un degré Celsius, tandis que la capacité thermique est la quantité de chaleur nécessaire pour élever la température d'une unité de masse d'une substance d'un degré Celsius.", "La chaleur spécifique est la quantité de chaleur nécessaire pour élever la température d'une unité de masse d'une substance d'un degré Celsius, tandis que la capacité thermique est la quantité de chaleur nécessaire pour élever la température d'un objet entier d'un degré Celsius.", "Il n'y a pas de différence."], answer: "La chaleur spécifique est la quantité de chaleur nécessaire pour élever la température d'une unité de masse d'une substance d'un degré Celsius, tandis que la capacité thermique est la quantité de chaleur nécessaire pour élever la température d'un objet entier d'un degré Celsius." },
        { question: "Qu'est-ce que la fusion ?", options: ["Le passage d'un état liquide à un état gazeux.", "Le passage d'un état gazeux à un état liquide.", "Le passage d'un état solide à un état liquide."], answer: "Le passage d'un état solide à un état liquide." },
        { question: "Qu'est-ce que la vaporisation ?", options: ["Le passage d'un état liquide à un état gazeux.", "Le passage d'un état solide à un état liquide.", "Le passage d'un état gazeux à un état liquide."], answer: "Le passage d'un état liquide à un état gazeux." },
        { question: "Quelle est la différence entre la chaleur latente de fusion et la chaleur latente de vaporisation ?", options: ["La chaleur latente de fusion est la quantité de chaleur nécessaire pour vaporiser une unité de masse d'une substance, tandis que la chaleur latente de vaporisation est la quantité de chaleur nécessaire pour faire fondre une unité de masse de la même substance.", "La chaleur latente de fusion est la quantité de chaleur nécessaire pour faire fondre une unité de masse d'une substance, tandis que la chaleur latente de vaporisation est la quantité de chaleur nécessaire pour vaporiser une unité de masse de la même substance.", "Il n'y a pas de différence."], answer: "La chaleur latente de fusion est la quantité de chaleur nécessaire pour faire fondre une unité de masse d'une substance, tandis que la chaleur latente de vaporisation est la quantité de chaleur nécessaire pour vaporiser une unité de masse de la même substance." },
        { question: "Qu'est-ce que la conductivité thermique ?", options: ["La capacité d'un matériau à résister à la chaleur.", "La capacité d'un matériau à stocker la chaleur.", "La capacité d'un matériau à conduire la chaleur."], answer: "La capacité d'un matériau à conduire la chaleur." },
        { question: "Quelle est l'unité de la conductivité thermique dans le Système International ?", options: ["Watt par mètre kelvin (W/m*K)", "Joule (J)", "Calorie (cal)"], answer: "Watt par mètre kelvin (W/m*K)" },
        { question: "Qu'est-ce que la convection thermique ?", options: ["Le transfert de chaleur par contact direct entre deux objets à des températures différentes.", "Le transfert de chaleur par le déplacement de masses fluides chaudes et froides.", "Le transfert de chaleur par le rayonnement électromagnétique."], answer: "Le transfert de chaleur par le déplacement de masses fluides chaudes et froides." },
        { question: "Qu'est-ce que la radiation thermique ?", options: ["Le transfert de chaleur par le déplacement de masses fluides chaudes et froides.", "Le transfert de chaleur par contact direct entre deux objets à des températures différentes.", "Le transfert de chaleur par le rayonnement électromagnétique."], answer: "Le transfert de chaleur par le rayonnement électromagnétique." },
        { question: "Qu'est-ce que la dilatation thermique ?", options: ["L'expansion d'un objet due à une augmentation de sa température.", "La contraction d'un objet due à une augmentation de sa température.", "La transformation d'un solide en liquide ou en gaz sous l'effet de la chaleur."], answer: "L'expansion d'un objet due à une augmentation de sa température." },
        { question: "Qu'est-ce que la loi de Gay-Lussac ?", options: ["Elle décrit la relation entre la température et le volume d'un gaz à pression constante.", "Elle décrit la relation entre la pression et le volume d'un gaz à température constante.", "Elle décrit la relation entre la pression et la température d'un gaz à volume constant."], answer: "Elle décrit la relation entre la pression et la température d'un gaz à volume constant." },
        { question: "Qu'est-ce que la loi de Charles ?", options: ["Elle décrit la relation entre la pression et le volume d'un gaz à température constante.", "Elle décrit la relation entre la pression et la température d'un gaz à volume constant.", "Elle décrit la relation entre la température et le volume d'un gaz à pression constante."], answer: "Elle décrit la relation entre la température et le volume d'un gaz à pression constante." },
        { question: "Qu'est-ce que la loi de Boyle-Mariotte ?", options: ["Elle décrit la relation entre la pression et le volume d'un gaz à température constante.", "Elle décrit la relation entre la température et le volume d'un gaz à pression constante.", "Elle décrit la relation entre la pression et la température d'un gaz à volume constant."], answer: "Elle décrit la relation entre la pression et le volume d'un gaz à température constante." },
        { question: "Qu'est-ce qu'un catalyseur ?", options: ["Une substance qui ralentit une réaction chimique.", "Une substance qui accélère une réaction chimique sans être consommée lors de la réaction.", "Une substance qui empêche une réaction chimique de se produire."], answer: "Une substance qui accélère une réaction chimique sans être consommée lors de la réaction." },
        { question: "Qu'est-ce que la catalyse homogène ?", options: ["Une réaction où le catalyseur est dans un état différent des réactifs.", "Une réaction où il n'y a pas de catalyseur.", "Une réaction où le catalyseur est dans le même état que les réactifs."], answer: "Une réaction où le catalyseur est dans le même état que les réactifs." },
        { question: "Qu'est-ce que la catalyse hétérogène ?", options: ["Une réaction où le catalyseur est dans un état différent des réactifs.", "Une réaction où le catalyseur est dans le même état que les réactifs.", "Une réaction où il n'y a pas de catalyseur."], answer: "Une réaction où le catalyseur est dans un état différent des réactifs." },
        { question: "Quelle est la différence entre un catalyseur et un inhibiteur ?", options: ["Un catalyseur ralentit une réaction chimique, tandis qu'un inhibiteur l'accélère.", "Un catalyseur accélère une réaction chimique, tandis qu'un inhibiteur la ralentit.", "Il n'y a pas de différence."], answer: "Un catalyseur accélère une réaction chimique, tandis qu'un inhibiteur la ralentit." },
        { question: "Qu'est-ce que la vitesse de réaction chimique ?", options: ["La vitesse à laquelle les produits sont convertis en réactifs.", "La quantité de réactifs nécessaire pour produire une certaine quantité de produits.", "La vitesse à laquelle les réactifs sont convertis en produits."], answer: "La vitesse à laquelle les réactifs sont convertis en produits." },
        { question: "Quels facteurs peuvent influencer la vitesse d'une réaction chimique ?", options: ["La température, la concentration des réactifs, la présence d'un catalyseur.", "La couleur des réactifs, la pression atmosphérique, la taille des réactifs.", "La masse des réactifs, la présence d'un inhibiteur, le temps de réaction."], answer: "La température, la concentration des réactifs, la présence d'un catalyseur." },
        { question: "Qu'est-ce que la constante d'équilibre ?", options: ["Une valeur qui exprime la vitesse à laquelle une réaction chimique se produit.", "Une valeur qui exprime la relation entre les concentrations des réactifs et des produits à l'équilibre dans une réaction chimique.", "Une valeur qui exprime la quantité totale de réactifs et de produits dans une réaction chimique."], answer: "Une valeur qui exprime la relation entre les concentrations des réactifs et des produits à l'équilibre dans une réaction chimique." },
        { question: "Qu'est-ce que la constante d'acidité ?", options: ["Une valeur qui mesure la concentration d'un acide.", "Une valeur qui mesure la quantité d'un acide.", "Une valeur qui mesure la force d'un acide."], answer: "Une valeur qui mesure la force d'un acide." },
        { question: "Qu'est-ce que le pH ?", options: ["Une mesure de l'acidité ou de la basicité d'une solution.", "Une mesure de la concentration en ions hydrogène dans une solution.", "Une mesure de la température d'une solution."], answer: "Une mesure de l'acidité ou de la basicité d'une solution." },
        { question: "Quelle est la différence entre un acide fort et un acide faible ?", options: ["Un acide fort se dissocie partiellement en solution, tandis qu'un acide faible se dissocie complètement.", "Un acide fort se dissocie complètement en solution, tandis qu'un acide faible se dissocie partiellement.", "Il n'y a pas de différence."], answer: "Un acide fort se dissocie complètement en solution, tandis qu'un acide faible se dissocie partiellement." },
        { question: "Qu'est-ce que l'hydrolyse ?", options: ["Une réaction chimique entre deux substances solubles dans l'eau.", "Une réaction chimique entre un acide et une base.", "Une réaction chimique entre une substance et de l'eau."], answer: "Une réaction chimique entre une substance et de l'eau." },
        { question: "Qu'est-ce qu'une solution acide ?", options: ["Une solution où la concentration en ions hydrogène est supérieure à la concentration en ions hydroxyde.", "Une solution où la concentration en ions hydroxyle est supérieure à la concentration en ions hydrogène.", "Une solution où la concentration en ions hydrogène est égale à la concentration en ions hydroxyde."], answer: "Une solution où la concentration en ions hydrogène est supérieure à la concentration en ions hydroxyde." },
        { question: "Qu'est-ce qu'une solution basique ?", options: ["Une solution où la concentration en ions hydrogène est supérieure à la concentration en ions hydroxyde.", "Une solution où la concentration en ions hydroxyde est supérieure à la concentration en ions hydrogène.", "Une solution où la concentration en ions hydrogène est égale à la concentration en ions hydroxyde."], answer: "Une solution où la concentration en ions hydroxyde est supérieure à la concentration en ions hydrogène." },
        { question: "Qu'est-ce que la neutralisation ?", options: ["Une réaction chimique entre un acide et un métal pour former de l'hydrogène.", "Une réaction chimique entre un métal et un non-métal pour former un composé ionique.", "Une réaction chimique entre un acide et une base pour former de l'eau et un sel."], answer: "Une réaction chimique entre un acide et une base pour former de l'eau et un sel." },
        { question: "Qu'est-ce qu'un oxydant ?", options: ["Une substance qui perd des électrons lors d'une réaction chimique.", "Une substance qui gagne des électrons lors d'une réaction chimique.", "Une substance qui ne subit aucun changement lors d'une réaction chimique."], answer: "Une substance qui gagne des électrons lors d'une réaction chimique." },
        { question: "Qu'est-ce qu'un réducteur ?", options: ["Une substance qui perd des électrons lors d'une réaction chimique.", "Une substance qui gagne des électrons lors d'une réaction chimique.", "Une substance qui ne subit aucun changement lors d'une réaction chimique."], answer: "Une substance qui perd des électrons lors d'une réaction chimique." },
        { question: "Qu'est-ce que l'oxydation ?", options: ["Le gain d'électrons par une substance lors d'une réaction chimique.", "Aucune des réponses ci-dessus.", "La perte d'électrons par une substance lors d'une réaction chimique."], answer: "La perte d'électrons par une substance lors d'une réaction chimique." },
        { question: "Qu'est-ce que la réduction ?", options: ["Le gain d'électrons par une substance lors d'une réaction chimique.", "La perte d'électrons par une substance lors d'une réaction chimique.", "Aucune des réponses ci-dessus."], answer: "Le gain d'électrons par une substance lors d'une réaction chimique." },
        { question: "Qu'est-ce que la pile électrochimique ?", options: ["Un dispositif qui convertit l'énergie électrique en énergie chimique.", "Un dispositif qui convertit l'énergie chimique en énergie électrique.", "Un dispositif qui stocke l'énergie électrique."], answer: "Un dispositif qui convertit l'énergie chimique en énergie électrique." },
        { question: "Qu'est-ce que l'électrolyse ?", options: ["Un processus chimique dans lequel une réaction spontanée produit un courant électrique.", "Un processus chimique dans lequel un courant électrique est stocké dans une solution.", "Un processus chimique dans lequel un courant électrique est utilisé pour provoquer une réaction non spontanée."], answer: "Un processus chimique dans lequel un courant électrique est utilisé pour provoquer une réaction non spontanée." },
        { question: "Qu'est-ce que la corrosion ?", options: ["La détérioration d'un matériau en raison de sa réaction avec son environnement.", "La transformation d'un métal en un oxyde métallique.", "La formation d'une couche protectrice sur la surface d'un métal."], answer: "La détérioration d'un matériau en raison de sa réaction avec son environnement." },
        { question: "Qu'est-ce qu'un polymère ?", options: ["Une substance formée par la combinaison de deux ou plusieurs éléments chimiques.", "Une macromolécule constituée de nombreuses sous-unités répétitives appelées monomères.", "Une molécule constituée de deux ou plusieurs atomes de différents éléments chimiques."], answer: "Une macromolécule constituée de nombreuses sous-unités répétitives appelées monomères." },
        { question: "Qu'est-ce que la polymérisation ?", options: ["Le processus de décomposition d'un polymère en monomères.", "Le processus de combinaison de deux ou plusieurs polymères.", "Le processus de formation d'un polymère à partir de monomères."], answer: "Le processus de formation d'un polymère à partir de monomères." },
        { question: "Qu'est-ce qu'une réaction d'addition ?", options: ["Une réaction dans laquelle deux molécules se combinent pour former une seule molécule sans formation de sous-produits.", "Une réaction dans laquelle une molécule est décomposée en deux ou plusieurs molécules.", "Une réaction dans laquelle un atome ou un groupe d'atomes est retiré d'une molécule."], answer: "Une réaction dans laquelle deux molécules se combinent pour former une seule molécule sans formation de sous-produits." },
        { question: "Qu'est-ce qu'une réaction de substitution ?", options: ["Une réaction dans laquelle deux molécules se combinent pour former une seule molécule sans formation de sous-produits.", "Une réaction dans laquelle un atome ou un groupe d'atomes est retiré d'une molécule.", "Une réaction dans laquelle une molécule est décomposée en deux ou plusieurs molécules."], answer: "Une réaction dans laquelle un atome ou un groupe d'atomes est retiré d'une molécule." },
        { question: "Qu'est-ce qu'une réaction de combustion ?", options: ["Une réaction chimique dans laquelle une substance est oxydée.", "Une réaction chimique dans laquelle une substance est réduite.", "Une réaction chimique dans laquelle une substance réagit avec l'oxygène pour produire de la chaleur et des produits de combustion."], answer: "Une réaction chimique dans laquelle une substance réagit avec l'oxygène pour produire de la chaleur et des produits de combustion." },
        { question: "Quel objet est tombé sur la tête de Newton ?", options: ["Une pomme", "Une orange", "Une brique"], answer: "Une pomme" },
        { question: "Que donne le mélange d'une lumière rouge avec une lumière verte ?", options: ["Magenta", "Cyan", "Jaune"], answer: "Jaune" },
    ];

    // Added Question Cut
    const shuffledQuestions = questions.sort(() => Math.random() - 0.5).slice(0, 5);
    const quizContainer = $("#question-container");
    const resultContainer = $("#result-container");
    const submitButton = $("#submit-btn");

    // Generate questions and options
    shuffledQuestions.forEach((questionObj, index) => {
        const options = questionObj.options.map(option => `<label><input type="radio" name="q${index}" value="${option}">${option}</label><br>`);
        quizContainer.append(`<div class="question">${questionObj.question}<br>${options.join("")}</div>`);
    });

    // Handle click on Submit button
    submitButton.click(function () {
        let correctAnswers = 0;

        questions.forEach((questionObj, index) => {
            const selectedOption = $(`input[name="q${index}"]:checked`).val();
            if (selectedOption === questionObj.answer) {
                correctAnswers++;
            }
        });

        // Addded score as a percentage
        const score = (correctAnswers / 5) * 100;
        const incorrectAnswers = 5 - correctAnswers;

        // Added display score and percentage of correct and incorrect answers
        resultContainer.html(`Score: ${score.toFixed(2)}%<br>
        Réponses correctes: ${correctAnswers}/5 (${((correctAnswers / 5) * 100).toFixed(2)}%)<br>
        Réponses fausses: ${incorrectAnswers}/5 (${((incorrectAnswers / 5) * 100).toFixed(2)}%)<br><br>`);

        // Added display result image based on score percentage
        const failImage = "platypus_fail.png"; // Fail image
        const partialImage = "platypus_partial.png"; // Partial success image
        const successImage = "platypus_success.png"; // Success image

        if (score < 50) {
            resultContainer.append(`<img src="${failImage}" alt="Fail Image">`);
        } else if (score < 75) {
            resultContainer.append(`<img src="${partialImage}" alt="Partial Success Image">`);
        } else {
            resultContainer.append(`<img src="${successImage}" alt="Success Image">`);
        }
    });
});